//! Tier-2 Claude context capture (cross-platform). Ported from the webview's
//! `src-tauri/src/claude_shim.rs` — it was already Tauri-free.
//!
//! Claude's exact context-window usage (window size, used %, per-component
//! tokens) is NOT in the transcript JSONL — it is only handed to a configured
//! `statusLine` command on stdin. To surface it, we intercept `claude` launches
//! inside Arbiter's own PTYs:
//!
//!   1. `shell.rs` prepends an Arbiter `bin/` dir (written here) to PATH for the
//!      spawned shell, so `claude` — and any alias that resolves it via PATH —
//!      hits our launcher.
//!   2. The launcher `exec`s the REAL claude with `--settings <file>` (generated
//!      here) that points `statusLine` at `<arbiter-bin> claude-statusline` and
//!      the Notification/PermissionRequest/Stop hooks at `<arbiter-bin> claude-hook`.
//!   3. Claude pipes its session JSON to those commands; we write it to
//!      `<capture-dir>/<session_id>.json` (and hook signals to `<hooks-dir>`),
//!      then call through to the user's original status line so it still renders.
//!
//! All JSON is built/parsed here in Rust. The launcher scripts contain no logic,
//! only a delegated `exec`.

use std::io::{Read, Write};
use std::path::{Path, PathBuf};

/// Absolute path to the real `claude` binary (resolved from PATH at spawn, with
/// our shim dir excluded so it never recurses into itself).
pub const REAL_CLAUDE_ENV: &str = "ARBITER_REAL_CLAUDE";
/// Path to the generated settings file the launcher passes via `--settings`.
pub const SETTINGS_ENV: &str = "ARBITER_CLAUDE_SETTINGS";
/// Directory where the capture subcommand writes `<session_id>.json`.
pub const CAPTURE_DIR_ENV: &str = "ARBITER_CAPTURE_DIR";
/// The user's original `statusLine.command`, if any, to call through to.
pub const ORIG_STATUSLINE_ENV: &str = "ARBITER_ORIG_STATUSLINE";
/// Directory where the hook subcommand writes per-session attention/stop signals.
pub const HOOKS_DIR_ENV: &str = "ARBITER_HOOKS_DIR";
/// Unique-per-pane id set on each spawned shell. It rides through
/// shell→claude→statusLine/hook subcommand, so a capture/hook can be keyed to the
/// EXACT pane that launched Claude — robust under many simultaneous launches and
/// when several panes share a cwd (cwd alone can't disambiguate).
pub const PANE_ID_ENV: &str = "ARBITER_PANE_ID";
/// The shim `bin/` dir prepended to PATH (set by `shell.rs`). It rides the
/// environment into any process the shell launches — including a nested Arbiter
/// (`cargo run` from inside the installed app) — so that nested instance can skip
/// the PARENT's shim when resolving the real `claude` and never chain shim→shim.
pub const SHIM_BIN_ENV: &str = "ARBITER_SHIM_BIN";

/// Marker in the first bytes of every launcher we generate (see `write_launchers`).
/// Lets the resolver tell a sibling Arbiter's shim from the genuine `claude`.
const LAUNCHER_MARKER: &[u8] = b"Generated by Arbiter";

/// Subdir (under app-data) that holds the shim `bin/` and generated settings.
const SHIM_SUBDIR: &str = "claude-shim";
/// Subdir (under app-data) that holds per-session capture files.
pub const CAPTURE_SUBDIR: &str = "claude-sessions";
/// Subdir (under app-data) that holds per-session hook signal files.
pub const HOOKS_SUBDIR: &str = "claude-hooks";

/// Append a diagnostic line to `<temp>/arbiter-claude-debug.log` when
/// `ARBITER_CLAUDE_DEBUG` is set. Off by default (it would otherwise grow
/// unbounded — the statusLine fires on every render). The temp dir is shared
/// down the shell→claude→subcommand chain, so all steps land in one findable
/// file even though the subcommands' stderr is invisible.
pub fn debug_log(msg: &str) {
    if std::env::var_os("ARBITER_CLAUDE_DEBUG").is_none() {
        return;
    }
    let ts = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    let path = std::env::temp_dir().join("arbiter-claude-debug.log");
    if let Ok(mut f) = std::fs::OpenOptions::new().create(true).append(true).open(&path) {
        use std::io::Write;
        let _ = writeln!(f, "[{ts}] {msg}");
    }
}

// ── Capture subcommand (`arbiter claude-statusline`) ─────────────────────────

/// Entry point for `claude-statusline`, invoked by Claude as its statusLine
/// command (via our injected `--settings`). Reads Claude's status JSON from
/// stdin, persists it keyed by `session_id`, then forwards to the user's
/// original status line so it still renders. Runs headless and returns.
pub fn run_statusline_capture() {
    let mut buf = Vec::new();
    if std::io::stdin().read_to_end(&mut buf).is_err() {
        return;
    }

    let sid = extract_session_id(&buf);
    // Key the capture by our pane id (so it binds to the EXACT pane that launched
    // Claude — robust when several panes share a cwd / launch at once). Falls back
    // to the session id when Claude wasn't launched in one of our shells.
    let key = std::env::var(PANE_ID_ENV)
        .ok()
        .filter(|s| !s.is_empty() && s.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_'))
        .or_else(|| sid.clone());
    debug_log(&format!(
        "statusline: invoked key={:?} session={:?} CAPTURE_DIR={:?} bytes={}",
        key,
        sid,
        std::env::var(CAPTURE_DIR_ENV).ok(),
        buf.len(),
    ));
    if let (Ok(dir), Some(key)) = (std::env::var(CAPTURE_DIR_ENV), key) {
        write_capture(Path::new(&dir), &key, &buf);
        debug_log(&format!("statusline: wrote capture to {dir}/{key}.json"));
    }

    if let Ok(orig) = std::env::var(ORIG_STATUSLINE_ENV) {
        if !orig.trim().is_empty() {
            forward_to_original(&orig, &buf);
        }
    }
}

/// Entry point for `claude-hook`, invoked by Claude's Notification /
/// PermissionRequest / Stop hooks. Reads the hook JSON from stdin and writes a
/// per-session signal file (`<HOOKS_DIR>/<session_id>.json`) the watcher routes
/// to the matching pane. Permission prompts/elicitation → `attention`; turn end
/// (`Stop`) → `stop`.
pub fn run_hook_signal() {
    let mut buf = Vec::new();
    if std::io::stdin().read_to_end(&mut buf).is_err() {
        return;
    }
    let v: serde_json::Value = match serde_json::from_slice(&buf) {
        Ok(v) => v,
        Err(_) => return,
    };
    let Some(session_id) = v.get("session_id").and_then(|s| s.as_str()) else { return };
    if session_id.is_empty()
        || !session_id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_')
    {
        return;
    }
    let event = v.get("hook_event_name").and_then(|s| s.as_str()).unwrap_or("");
    let ntype = v.get("notification_type").and_then(|s| s.as_str()).unwrap_or("");
    let signal = match event {
        "Stop" => "stop",
        "PermissionRequest" => "attention",
        "Notification" => match ntype {
            // `idle_prompt` is intentionally excluded — it fires after ~60s idle
            // and would turn a merely-idle pane amber (we keep idle grey).
            //
            // `elicitation_dialog` (AskUserQuestion) is ALSO excluded: it's detected
            // level-based from the rendered menu (`VtTerm::visible_menu`), which
            // clears the instant the user escapes/answers. The hook is edge-only and
            // would get STUCK on escape (no spinner/Stop follows to clear it).
            "permission_prompt" => "attention",
            _ => return,
        },
        _ => return,
    };

    let Ok(dir) = std::env::var(HOOKS_DIR_ENV) else { return };
    let dir = Path::new(&dir);
    if std::fs::create_dir_all(dir).is_err() {
        return;
    }
    // A nonce makes every write distinct so the watcher fires even on a repeat.
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis())
        .unwrap_or(0);
    let body = format!("{{\"signal\":\"{signal}\",\"nonce\":{nonce}}}");
    let final_path = dir.join(format!("{session_id}.json"));
    let tmp_path = dir.join(format!("{session_id}.json.tmp"));
    if std::fs::write(&tmp_path, body).is_ok() {
        let _ = std::fs::rename(&tmp_path, &final_path);
    }
}

/// Parse just the `session_id` from Claude's status JSON.
fn extract_session_id(buf: &[u8]) -> Option<String> {
    let v: serde_json::Value = serde_json::from_slice(buf).ok()?;
    let id = v.get("session_id")?.as_str()?;
    if id.is_empty() || !id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-' || b == b'_') {
        return None;
    }
    Some(id.to_string())
}

/// Atomically write the captured JSON to `<dir>/<session_id>.json`.
fn write_capture(dir: &Path, session_id: &str, buf: &[u8]) {
    if std::fs::create_dir_all(dir).is_err() {
        return;
    }
    let final_path = dir.join(format!("{session_id}.json"));
    let tmp_path = dir.join(format!("{session_id}.json.tmp"));
    if std::fs::write(&tmp_path, buf).is_ok() {
        let _ = std::fs::rename(&tmp_path, &final_path);
    }
}

/// Run the user's original `statusLine.command` with the same stdin so Claude
/// renders it unchanged.
fn forward_to_original(orig: &str, stdin_bytes: &[u8]) {
    #[cfg(windows)]
    let mut cmd = {
        // Claude statusLines are conventionally Git-Bash scripts (e.g.
        // `bash /c/Users/.../statusline.sh`). Running such a command through `cmd /C`
        // fails — `bash` from cmd resolves to WSL or is absent, and the /c/... MSYS
        // path is invalid there (the exact failure the user hit). When the command
        // looks bash-based and Git Bash is installed, run it through Git Bash so it
        // renders; otherwise fall back to cmd for plain cmd/PowerShell commands.
        let looks_bash = orig.contains(".sh")
            || orig.trim_start().starts_with("bash ")
            || orig.trim_start().starts_with("sh ");
        match crate::shell::detect_git_bash().filter(|_| looks_bash) {
            Some(bash) => {
                debug_log(&format!("forward: via git-bash {bash:?} orig={orig:?}"));
                let mut c = std::process::Command::new(bash);
                c.arg("-c").arg(orig);
                c
            }
            None => {
                debug_log(&format!("forward: via cmd /C orig={orig:?} (no git-bash / not bash)"));
                let mut c = std::process::Command::new("cmd");
                c.arg("/C").arg(orig);
                c
            }
        }
    };
    #[cfg(not(windows))]
    let mut cmd = {
        let mut c = std::process::Command::new("sh");
        c.arg("-c").arg(orig);
        c
    };

    cmd.stdin(std::process::Stdio::piped());
    // On Windows: (1) CREATE_NO_WINDOW so spawning cmd/bash from this GUI-subsystem
    // process doesn't flash a console window on every status-line render; (2) discard
    // the child's stderr so a failed launch (e.g. `bash` not resolvable from cmd,
    // invalid /c/... path) can't leak its error text into the terminal / Claude's
    // status area (the reported `0x800700E8`). Stdout still passes through, so a
    // working status line renders normally.
    #[cfg(windows)]
    {
        use std::os::windows::process::CommandExt;
        cmd.creation_flags(0x0800_0000); // CREATE_NO_WINDOW
        cmd.stderr(std::process::Stdio::null());
    }
    let mut child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            debug_log(&format!("forward: spawn failed: {e}"));
            return;
        }
    };
    if let Some(mut stdin) = child.stdin.take() {
        let _ = stdin.write_all(stdin_bytes);
    }
    let status = child.wait();
    debug_log(&format!("forward: child exited {status:?}"));
}

// ── Reading captures back (the footer's Tier-2 stats) ────────────────────────

/// Parsed Claude statusLine capture: stats + the cwd/session_id used to bind it
/// to a pane. `used_percent`/token usage are None/0 until the first turn.
#[derive(Clone, Debug)]
pub struct Capture {
    pub session_id: String,
    pub cwd: String,
    /// The capture file's stem — the pane id (`PANE_ID_ENV`) when Claude ran in one
    /// of our shells, so a capture binds to the exact pane; else the session id
    /// (legacy / Claude launched outside our shell). The primary bind key.
    pub key: String,
    /// The capture file's last-modified time — fallback to pick the LIVE session
    /// when binding by cwd (the live one is written most recently).
    pub mtime: std::time::SystemTime,
    pub model: Option<String>,
    pub context_size: Option<u64>,
    pub used_percent: Option<f64>,
    pub input_tokens: u64,
    pub output_tokens: u64,
    pub cache_read: u64,
    pub cache_write: u64,
    pub cost_usd: f64,
}

/// Parse one capture JSON (the shape Claude's statusLine emits).
pub fn parse_capture(bytes: &[u8]) -> Option<Capture> {
    let v: serde_json::Value = serde_json::from_slice(bytes).ok()?;
    let session_id = v.get("session_id")?.as_str()?.to_string();
    let cwd = v
        .get("cwd")
        .and_then(|c| c.as_str())
        .or_else(|| v.pointer("/workspace/current_dir").and_then(|c| c.as_str()))?
        .to_string();
    let cw = v.get("context_window");
    let usage = cw.and_then(|c| c.get("current_usage"));
    let tok = |k: &str| usage.and_then(|u| u.get(k)).and_then(|n| n.as_u64()).unwrap_or(0);
    Some(Capture {
        session_id,
        cwd,
        key: String::new(),                       // filled in by read_captures (file stem)
        mtime: std::time::SystemTime::UNIX_EPOCH, // filled in by read_captures
        model: v.pointer("/model/display_name").and_then(|m| m.as_str()).map(str::to_string),
        context_size: cw.and_then(|c| c.get("context_window_size")).and_then(|n| n.as_u64()),
        used_percent: cw.and_then(|c| c.get("used_percentage")).and_then(|n| n.as_f64()),
        input_tokens: tok("input_tokens"),
        output_tokens: tok("output_tokens"),
        cache_write: tok("cache_creation_input_tokens"),
        cache_read: tok("cache_read_input_tokens"),
        cost_usd: v.pointer("/cost/total_cost_usd").and_then(|n| n.as_f64()).unwrap_or(0.0),
    })
}

/// Read + parse every `<sid>.json` in the capture dir.
pub fn read_captures(dir: &Path) -> Vec<Capture> {
    let mut out = Vec::new();
    if let Ok(rd) = std::fs::read_dir(dir) {
        for entry in rd.flatten() {
            let p = entry.path();
            if p.extension().and_then(|e| e.to_str()) == Some("json") {
                if let Ok(bytes) = std::fs::read(&p) {
                    if let Some(mut c) = parse_capture(&bytes) {
                        c.key = p.file_stem().and_then(|s| s.to_str()).unwrap_or("").to_string();
                        c.mtime = entry
                            .metadata()
                            .and_then(|m| m.modified())
                            .unwrap_or(std::time::SystemTime::UNIX_EPOCH);
                        out.push(c);
                    }
                }
            }
        }
    }
    out
}

// ── Spawn-time setup (called from shell.rs) ──────────────────────────────────

/// Everything `shell.rs` needs to wire the spawned shell for interception.
pub struct ShimSetup {
    pub bin_dir: PathBuf,
    pub real_claude: Option<PathBuf>,
    pub settings_file: PathBuf,
    pub capture_dir: PathBuf,
    pub hooks_dir: PathBuf,
    pub orig_statusline: Option<String>,
}

/// Prepare the shim dir, launcher(s), and settings file under `data_dir`.
/// Returns `None` only if a required file write fails.
pub fn setup(data_dir: &Path, original_path: &str, arbiter_bin: &Path) -> Option<ShimSetup> {
    let shim_dir = data_dir.join(SHIM_SUBDIR);
    let bin_dir = shim_dir.join("bin");
    let capture_dir = data_dir.join(CAPTURE_SUBDIR);
    let hooks_dir = data_dir.join(HOOKS_SUBDIR);

    // May be None when the GUI's PATH lacks claude (Finder-launched .app); not
    // fatal — the launcher falls back to a PATH scan in the spawned shell. The
    // parent shim (if this Arbiter was launched from inside another) is skipped so
    // we resolve the genuine binary, never a shim that would exec us right back.
    let parent_shim = std::env::var_os(SHIM_BIN_ENV).map(PathBuf::from);
    let real_claude = find_real_claude(original_path, &bin_dir, parent_shim.as_deref());

    std::fs::create_dir_all(&bin_dir).ok()?;
    std::fs::create_dir_all(&capture_dir).ok()?;
    std::fs::create_dir_all(&hooks_dir).ok()?;

    let settings_file = shim_dir.join("settings.json");
    write_settings(&settings_file, arbiter_bin)?;
    write_launchers(&bin_dir)?;

    debug_log(&format!(
        "setup: bin_dir={} real_claude={:?} settings={} arbiter_bin={}",
        bin_dir.display(),
        real_claude,
        settings_file.display(),
        arbiter_bin.display(),
    ));

    Some(ShimSetup {
        bin_dir,
        real_claude,
        settings_file,
        capture_dir,
        hooks_dir,
        orig_statusline: read_user_statusline(),
    })
}

/// Resolve the real `claude` by scanning `original_path`, skipping any Arbiter
/// shim. We skip three things, all of which would otherwise make the launcher
/// `exec` *another* shim instead of the genuine binary — an infinite shim→shim
/// loop (the symptom: `claude` hangs, prints nothing). This happens when one
/// Arbiter is launched from inside another (e.g. `cargo run` from the installed
/// app): the child inherits the parent's shim `bin/` at the front of PATH.
///   1. our own `bin_dir` (never recurse into ourselves);
///   2. the PARENT shim's `bin/` (inherited via `ARBITER_SHIM_BIN`);
///   3. belt-and-suspenders: any candidate that is one of our generated launchers
///      (covers a stale/sibling shim dir not named by `ARBITER_SHIM_BIN`).
fn find_real_claude(original_path: &str, bin_dir: &Path, parent_shim: Option<&Path>) -> Option<PathBuf> {
    #[cfg(windows)]
    let names: &[&str] = &["claude.exe", "claude.cmd", "claude.bat", "claude"];
    #[cfg(not(windows))]
    let names: &[&str] = &["claude"];

    let sep = if cfg!(windows) { ';' } else { ':' };
    for dir in original_path.split(sep) {
        if dir.is_empty() {
            continue;
        }
        let dir = Path::new(dir);
        if dir == bin_dir || parent_shim == Some(dir) {
            continue;
        }
        for name in names {
            let candidate = dir.join(name);
            if candidate.is_file() && !is_arbiter_launcher(&candidate) {
                return Some(candidate);
            }
        }
    }
    None
}

/// Whether `path` is one of Arbiter's own generated `claude` launchers, detected
/// by the marker in its first bytes. Genuine `claude` is a binary / node wrapper
/// that never carries it, so this only ever skips a sibling Arbiter's shim.
fn is_arbiter_launcher(path: &Path) -> bool {
    let mut buf = [0u8; 128];
    let n = match std::fs::File::open(path).and_then(|mut f| f.read(&mut buf)) {
        Ok(n) => n,
        Err(_) => return false,
    };
    buf[..n].windows(LAUNCHER_MARKER.len()).any(|w| w == LAUNCHER_MARKER)
}

/// Write the launcher(s) into `bin_dir`. The launcher `exec`s the real claude
/// with our `--settings`, forwarding all args; no logic.
fn write_launchers(bin_dir: &Path) -> Option<()> {
    const POSIX_LAUNCHER: &str = r#"#!/bin/sh
# Generated by Arbiter to intercept `claude` and capture Claude context usage.
_real="$ARBITER_REAL_CLAUDE"
if [ -z "$_real" ] || [ ! -x "$_real" ]; then
	_self=$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)
	_save=$IFS; IFS=:
	for _d in $PATH; do
		[ "$_d" = "$_self" ] && continue
		[ "$_d" = "$ARBITER_SHIM_BIN" ] && continue
		[ -x "$_d/claude" ] || continue
		# Skip a different Arbiter instance's shim; else we exec a shim that
		# execs us, forever. (Mirror of find_real_claude's marker check.)
		head -c 128 "$_d/claude" 2>/dev/null | grep -q "Generated by Arbiter" && continue
		_real="$_d/claude"; break
	done
	IFS=$_save
fi
[ -z "$_real" ] && { echo "arbiter: real 'claude' not found" >&2; exit 127; }
if [ -n "$ARBITER_CLAUDE_SETTINGS" ]; then
	exec "$_real" --settings "$ARBITER_CLAUDE_SETTINGS" "$@"
fi
exec "$_real" "$@"
"#;
    let posix_path = bin_dir.join("claude");
    std::fs::write(&posix_path, POSIX_LAUNCHER).ok()?;
    make_executable(&posix_path);

    #[cfg(windows)]
    {
        const WINDOWS_LAUNCHER: &str = "@echo off\r\n\
rem Generated by Arbiter to intercept claude and capture Claude context usage.\r\n\
if not defined ARBITER_REAL_CLAUDE (echo arbiter: ARBITER_REAL_CLAUDE not set 1>&2 & exit /b 127)\r\n\
if defined ARBITER_CLAUDE_SETTINGS (\r\n\
call \"%ARBITER_REAL_CLAUDE%\" --settings \"%ARBITER_CLAUDE_SETTINGS%\" %*\r\n\
) else (\r\n\
call \"%ARBITER_REAL_CLAUDE%\" %*\r\n\
)\r\n\
exit /b %ERRORLEVEL%\r\n";
        std::fs::write(bin_dir.join("claude.cmd"), WINDOWS_LAUNCHER).ok()?;
    }
    Some(())
}

#[cfg(unix)]
fn make_executable(path: &Path) {
    use std::os::unix::fs::PermissionsExt;
    if let Ok(meta) = std::fs::metadata(path) {
        let mut perms = meta.permissions();
        perms.set_mode(0o755);
        let _ = std::fs::set_permissions(path, perms);
    }
}
#[cfg(not(unix))]
fn make_executable(_path: &Path) {}

/// Write the settings file pointing `statusLine` at our capture subcommand and
/// the attention hooks at our hook subcommand. Claude merges this with the
/// user's own settings/hooks (loaded via `--settings`).
fn write_settings(path: &Path, arbiter_bin: &Path) -> Option<()> {
    // Commands run via a shell; quote the path. On Windows that shell may be Git
    // Bash, where backslashes are escapes — normalise to forward slashes (valid
    // for cmd/PowerShell/Git Bash alike).
    #[cfg(windows)]
    let bin = arbiter_bin.display().to_string().replace('\\', "/");
    #[cfg(not(windows))]
    let bin = arbiter_bin.display().to_string();
    let status_command = format!("\"{bin}\" claude-statusline");
    let hook_command = format!("\"{bin}\" claude-hook");
    let hook_entry = serde_json::json!({
        "hooks": [{ "type": "command", "command": hook_command }]
    });
    let settings = serde_json::json!({
        "statusLine": { "type": "command", "command": status_command, "padding": 0 },
        "hooks": {
            "Notification": [hook_entry.clone()],
            "PermissionRequest": [hook_entry.clone()],
            "Stop": [hook_entry],
        }
    });
    let json = serde_json::to_string_pretty(&settings).ok()?;
    std::fs::write(path, json).ok()?;
    Some(())
}

/// Read the user's configured `statusLine.command` (for call-through), honoring
/// `CLAUDE_CONFIG_DIR` and falling back to `~/.claude`.
fn read_user_statusline() -> Option<String> {
    let settings_path = claude_config_dir()?.join("settings.json");
    let data = std::fs::read_to_string(settings_path).ok()?;
    let v: serde_json::Value = serde_json::from_str(&data).ok()?;
    v.get("statusLine")?.get("command")?.as_str().map(str::to_string)
}

/// Resolve Claude's config dir: `$CLAUDE_CONFIG_DIR` if set, else `~/.claude`.
pub fn claude_config_dir() -> Option<PathBuf> {
    if let Ok(dir) = std::env::var("CLAUDE_CONFIG_DIR") {
        if !dir.trim().is_empty() {
            return Some(PathBuf::from(dir));
        }
    }
    let home = std::env::var("HOME").or_else(|_| std::env::var("USERPROFILE")).ok()?;
    Some(PathBuf::from(home).join(".claude"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmpdir(tag: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let d = std::env::temp_dir().join(format!("arbiter-shimtest-{}-{tag}-{nanos}", std::process::id()));
        std::fs::create_dir_all(&d).unwrap();
        d
    }

    /// Write a `claude` file in `dir`: a marker-carrying Arbiter launcher when
    /// `shim`, else a stand-in for the genuine binary (a node wrapper, no marker).
    fn put_claude(dir: &Path, shim: bool) -> PathBuf {
        let body = if shim {
            "#!/bin/sh\n# Generated by Arbiter to intercept claude.\nexec true\n"
        } else {
            "#!/usr/bin/env node\nconsole.log('real claude');\n"
        };
        let p = dir.join("claude");
        std::fs::write(&p, body).unwrap();
        p
    }

    #[test]
    fn is_arbiter_launcher_only_matches_our_scripts() {
        let d = tmpdir("marker");
        assert!(is_arbiter_launcher(&put_claude(&d, true)), "our launcher must be detected");
        assert!(!is_arbiter_launcher(&put_claude(&d, false)), "genuine claude must not match");
        assert!(!is_arbiter_launcher(&d.join("nope")), "missing file must not match");
        let _ = std::fs::remove_dir_all(&d);
    }

    #[test]
    fn find_real_claude_skips_self_and_parent_and_sibling_shims() {
        let root = tmpdir("resolve");
        let own = root.join("own");
        let parent = root.join("parent");
        let sibling = root.join("sibling");
        let genuine = root.join("genuine");
        for d in [&own, &parent, &sibling, &genuine] {
            std::fs::create_dir_all(d).unwrap();
        }
        put_claude(&own, true); // our own shim
        put_claude(&parent, true); // the launching Arbiter's shim (ARBITER_SHIM_BIN)
        put_claude(&sibling, true); // a stale Arbiter shim, NOT named by the env var
        let real = put_claude(&genuine, false); // the binary we want

        let sep = if cfg!(windows) { ";" } else { ":" };
        // own first (skipped as bin_dir), then parent (env), then sibling (marker),
        // then the genuine binary — which is what must be returned.
        let path = [&own, &parent, &sibling, &genuine]
            .map(|d| d.display().to_string())
            .join(sep);

        let got = find_real_claude(&path, &own, Some(&parent));
        assert_eq!(got.as_deref(), Some(real.as_path()));

        // Even with no ARBITER_SHIM_BIN known, the marker check alone keeps us off
        // every shim and on the genuine binary.
        let got_no_env = find_real_claude(&path, &own, None);
        assert_eq!(got_no_env.as_deref(), Some(real.as_path()));

        let _ = std::fs::remove_dir_all(&root);
    }
}
